### ISSUE TITLE
Cannot delete clients

### ISSUE THREAD

**Issue by danhooper** [danhooper/mindwell#30]
Perhaps when acting as another user?

**Comment by danhooper** [comment]
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/Mindwell/Client/rest_views.py", line 79, in rest_indiv_dos
    dos.delete()
AttributeError: 'NoneType' object has no attribute 'delete'

**Comment by danhooper** [comment]
Minor version 388352727082156138

exceptions.AttributeError@Mindwell/Client/rest_views.py:79 (at least 2 occurrences)

Handler:    main.pyc
URL:    https://mind-well.appspot.com/Mindwell/rest/dos/{id}
Stacktrace: 
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/base/data/home/apps/s~mindwellonline/3-1-0-20151105-angular-dev.388352727082156138/Mindwell/Client/rest_views.py", line 79, in rest_indiv_dos
    dos.delete()
AttributeError: 'NoneType' object has no attribute 'delete'
